TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this
DB += flo_aiao.db
DB += flo_DAS1a.db
DB += flo_DAS1b.db
DB += flo_DAS2a.db
DB += flo_DAS2b.db
DB += flo_DASa.db
DB += flo_log.db
DB += flo_PLC.db
DB += flo_stagp.db
DB += flo_temp.db
DB += flo_wdmon.db
DB += sim.db



#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_template = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
